CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    price BIGINT NOT NULL CHECK (price >= 0),
    stock INTEGER NOT NULL CHECK (stock >= 0),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO products (
    id,
    name,
    price,
    stock
)
VALUES (
    1,
    'Mechanical Keyboard',
    1200000,
    10
)
ON CONFLICT (id) DO NOTHING;